package com.mantraproductions.ndi

/**
 * Cube LUTs, generated rather than stored.
 *
 * A 33 cube holds 35,937 triplets, roughly 1.5 MB of text. Every one of those
 * numbers comes from about ten constants in [LogCurves], so the app carries
 * the constants and writes the file when somebody asks for it. Six curves at
 * three sizes would be eighteen files and 30 MB shipped; instead it is one
 * function and a few hundred bytes of code, and any size can be produced,
 * including sizes nobody thought to pre-bake.
 *
 * The format is Adobe/IRIDAS .cube, which Resolve, Premiere, Final Cut,
 * Avid and every on-set monitor read. Blue varies slowest, red fastest,
 * which is the ordering the format requires and the easiest thing to get
 * backwards.
 */
object CubeLut {

    const val DEFAULT_SIZE = 33

    /**
     * A LUT that undoes [from] and leaves the image in [to].
     *
     * The everyday use is from a log curve to Rec.709: drop it on the footage
     * in any editor and the flat image becomes a normal one. The same call
     * with two log curves produces a conversion between them.
     */
    fun generate(
        from: LogCurves.Curve,
        to: LogCurves.Curve = LogCurves.Curve.REC709,
        size: Int = DEFAULT_SIZE,
        title: String? = null
    ): String {
        require(size in 2..64) { "cube size $size is outside what the format allows" }

        val sb = StringBuilder(size * size * size * 26 + 200)
        sb.append("# Generated by Mantra NDI\n")
        sb.append("# ").append(from.vendor).append(' ').append(from.displayName)
            .append(" to ").append(to.vendor).append(' ').append(to.displayName).append('\n')
        sb.append("# Computed from the published transfer functions, not resampled from a file\n")
        sb.append("TITLE \"")
            .append(title ?: "${from.displayName} to ${to.displayName}")
            .append("\"\n")
        sb.append("LUT_3D_SIZE ").append(size).append('\n')
        sb.append("DOMAIN_MIN 0.0 0.0 0.0\n")
        sb.append("DOMAIN_MAX 1.0 1.0 1.0\n")

        // One dimension of values, reused for all three channels: the transfer
        // function is per channel and identical across them, so this is 33
        // evaluations instead of 35,937 x 3.
        val mapped = DoubleArray(size) { i ->
            LogCurves.convert(from, to, i.toDouble() / (size - 1))
        }

        for (b in 0 until size) {
            for (g in 0 until size) {
                for (r in 0 until size) {
                    sb.append(fmt(mapped[r])).append(' ')
                        .append(fmt(mapped[g])).append(' ')
                        .append(fmt(mapped[b])).append('\n')
                }
            }
        }
        return sb.toString()
    }

    /** A filename that says what the LUT is without needing to be opened. */
    fun fileName(from: LogCurves.Curve, to: LogCurves.Curve, size: Int): String =
        "${from.vendor}_${from.displayName}_to_${to.displayName}_${size}.cube"
            .replace(' ', '_')
            .replace(".", "")
            .replace("_cube", ".cube")

    /**
     * A parsed LUT, held as a flat array in the format's own ordering so a
     * lookup is arithmetic rather than a search.
     */
    data class Lut3D(val size: Int, val data: FloatArray, val title: String) {
        /** Nearest-neighbour sample. Enough for a monitoring overlay. */
        fun sample(r: Float, g: Float, b: Float): FloatArray {
            val last = size - 1
            val ri = Math.round(r.coerceIn(0f, 1f) * last)
            val gi = Math.round(g.coerceIn(0f, 1f) * last)
            val bi = Math.round(b.coerceIn(0f, 1f) * last)
            val index = ((bi * size + gi) * size + ri) * 3
            return floatArrayOf(data[index], data[index + 1], data[index + 2])
        }

        override fun equals(other: Any?): Boolean =
            other is Lut3D && size == other.size && title == other.title &&
                    data.contentEquals(other.data)

        override fun hashCode(): Int = 31 * (31 * size + title.hashCode()) + data.contentHashCode()
    }

    /**
     * Reads a .cube file the operator supplied, for monitoring.
     *
     * Deliberately tolerant: real LUTs in the wild carry comments, blank
     * lines, tabs, CRLF endings and keywords in any order. Returns null rather
     * than throwing, because a bad file the operator picked is not a crash.
     */
    fun parse(text: String): Lut3D? {
        var size = -1
        var title = "Untitled"
        val values = ArrayList<Float>(35_937 * 3)

        for (rawLine in text.lineSequence()) {
            val line = rawLine.trim()
            if (line.isEmpty() || line.startsWith("#")) continue

            when {
                line.startsWith("LUT_3D_SIZE", ignoreCase = true) ->
                    size = line.substringAfter(' ').trim().toIntOrNull() ?: return null

                line.startsWith("TITLE", ignoreCase = true) ->
                    title = line.substringAfter(' ').trim().trim('"')

                // A 1D LUT is a different thing and silently reading it as 3D
                // would produce a plausible looking wrong image.
                line.startsWith("LUT_1D_SIZE", ignoreCase = true) -> return null

                line.startsWith("DOMAIN_", ignoreCase = true) -> Unit

                else -> {
                    val parts = line.split(Regex("\\s+"))
                    if (parts.size < 3) continue
                    val r = parts[0].toFloatOrNull() ?: continue
                    val g = parts[1].toFloatOrNull() ?: continue
                    val b = parts[2].toFloatOrNull() ?: continue
                    values.add(r); values.add(g); values.add(b)
                }
            }
        }

        if (size < 2) return null
        val expected = size * size * size * 3
        if (values.size != expected) return null

        return Lut3D(size, values.toFloatArray(), title)
    }

    private fun fmt(v: Double): String {
        // Six decimals is below the precision of a 10-bit signal and keeps the
        // file roughly a third the size of the float formatting most tools emit.
        val rounded = Math.round(v.coerceIn(0.0, 1.0) * 1_000_000.0) / 1_000_000.0
        return rounded.toString()
    }
}
